version: 2
updates:
  - package-ecosystem: cargo
    directory: /src-tauri
    groups:
      tauri:
        patterns:
          - "tauri*"
          - "wry"
          - "tao"

  - package-ecosystem: npm
    directory: /
    groups:
      tauri:
        patterns:
          - "@tauri-apps/*"
      vue:
        patterns:
          - "vue*"
          - "pinia"
          - "@vitejs/*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
